name: pep_blog_reg-40654              # Имя compose stack
services:
  my_name:                            # Имя ?
    container_name: PostgresSQL-40654 # Имя container в stack
    image: postgres                   # Название образа на котором основан контейнер
    ports:
      - "40654:5432"                  # forwarding port
    environment:
      POSTGRES_USER: admin            # Имя администратора db
      POSTGRES_PASSWORD: qQ111111     # Пароль администратора db
      POSTGRES_DB: pep_db             # Имя db